version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi_app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src   # Monta el código local
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    env_file:
      - .env   # carga todas las variables
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: api_users_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
