services:
  backend:
    build: .
    container_name: fastapi_app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src   # Monta el código local
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    env_file:
      - .env   # carga todas las variables
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_postgre
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      POSTGRES_DB: ${POSTGRE_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRE_PORT}:5432"

volumes:
  db_data:
